"""WIP

Revision ID: 59ddd06897c6
Revises: b9d2debecb89
Create Date: 2021-07-15 12:56:30.788481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ddd06897c6'
down_revision = 'b9d2debecb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('passport')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport', sa.INTEGER(), server_default=sa.text("'1234123456'"), nullable=False))

    # ### end Alembic commands ###
