"""add date

Revision ID: 8c277538786a
Revises: 59ddd06897c6
Create Date: 2021-07-15 13:33:36.910283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c277538786a'
down_revision = '59ddd06897c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False, server_default='2021-01-01'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
