"""add doctor.specialty

Revision ID: b9d2debecb89
Revises: 29e015ad2001
Create Date: 2021-07-13 21:27:44.739630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d2debecb89'
down_revision = '29e015ad2001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_doctor_specialty_id_specialty'), 'specialty', ['specialty_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_doctor_specialty_id_specialty'), type_='foreignkey')
        batch_op.drop_column('specialty_id')

    # ### end Alembic commands ###
