"""init

Revision ID: d0d04c2130c5
Revises: cb75531cdb4b
Create Date: 2021-07-13 17:44:52.126515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d04c2130c5'
down_revision = 'cb75531cdb4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_time_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointment_record_time_id_record_time'), 'record_time', ['record_time_id'], ['id'])
        batch_op.drop_column('time')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_appointment_record_time_id_record_time'), type_='foreignkey')
        batch_op.drop_column('record_time_id')

    # ### end Alembic commands ###
